from typing import Protocol
from uuid import UUID

from ascend.domain.captures.entity import Capture


class CaptureRepository(Protocol):
    def save(self, capture: Capture) -> None: ...

    def get(self, capture_id: UUID) -> Capture | None: ...

    def list(self, limit: int = 50, offset: int = 0, q: str | None = None) -> list[Capture]: ...

    def list_by_ids(self, ids: "list[UUID]") -> "list[Capture]": ...

    def delete(self, capture_id: UUID) -> None: ...
