from typing import Protocol
from uuid import UUID

from ascend.domain.relationships.entity import Relationship, RelationshipType


class RelationshipRepository(Protocol):
    def save(self, relationship: Relationship) -> None: ...

    def get(self, relationship_id: UUID) -> Relationship | None: ...

    def delete(self, relationship_id: UUID) -> None: ...

    def list_outgoing(self, entity_id: UUID) -> list[Relationship]: ...

    def list_incoming(self, entity_id: UUID) -> list[Relationship]: ...

    def list_by_type(self, relationship_type: RelationshipType) -> list[Relationship]: ...
