from typing import Protocol
from uuid import UUID

from ascend.domain.collections.entity import Collection, Membership


class CollectionRepository(Protocol):
    def save(self, collection: Collection) -> None: ...

    def get(self, collection_id: UUID) -> Collection | None: ...

    def get_by_name(self, name: str) -> Collection | None: ...

    def delete(self, collection_id: UUID) -> None: ...

    def list(
        self,
        q: str | None = None,
        color: str | None = None,
        icon: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Collection]: ...

    def list_by_ids(self, ids: "list[UUID]") -> "list[Collection]": ...


class MembershipRepository(Protocol):
    def save(self, membership: Membership) -> None: ...

    def get(self, membership_id: UUID) -> Membership | None: ...

    def delete(self, membership_id: UUID) -> None: ...

    def find(self, collection_id: UUID, entity_id: UUID) -> Membership | None: ...

    def list_by_collection(self, collection_id: UUID) -> list[Membership]: ...

    def list_by_entity(self, entity_id: UUID) -> list[Membership]: ...

    def delete_by_collection(self, collection_id: UUID) -> None: ...

    def delete_by_entity(self, entity_id: UUID) -> None: ...
