"""Add sources table

Revision ID: 3fc5a00097d1
Revises: 789c7891002b
Create Date: 2026-07-11 17:03:54.636618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fc5a00097d1'
down_revision: Union[str, Sequence[str], None] = '789c7891002b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('WEB_ARTICLE', 'YOUTUBE', 'PDF', 'BOOK', 'MARKDOWN', 'IMAGE', 'AUDIO', 'VIDEO', 'TWEET', 'LOCAL_FILE', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_title'), 'sources', ['title'], unique=False)
    op.create_index(op.f('ix_sources_uri'), 'sources', ['uri'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_uri'), table_name='sources')
    op.drop_index(op.f('ix_sources_title'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
