"""Add relationships table

Revision ID: 789c7891002b
Revises: 95d3f2f36019
Create Date: 2026-07-11 16:34:04.566580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '789c7891002b'
down_revision: Union[str, Sequence[str], None] = '95d3f2f36019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_id', sa.Uuid(), nullable=False),
    sa.Column('from_type', sa.Enum('CAPTURE', 'CONCEPT', name='entitytype'), nullable=False),
    sa.Column('to_id', sa.Uuid(), nullable=False),
    sa.Column('to_type', sa.Enum('CAPTURE', 'CONCEPT', name='entitytype'), nullable=False),
    sa.Column('relationship_type', sa.Enum('RELATED_TO', 'DERIVED_FROM', 'REFERENCES', 'SUPPORTS', 'CONTRADICTS', 'SUMMARIZES', 'EXPLAINS', 'GENERATED_FROM', 'TAGGED_AS', name='relationshiptype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Enum('SYSTEM', 'USER', 'AI', 'IMPORT', 'SYNC', name='creatortype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_from_id'), 'relationships', ['from_id'], unique=False)
    op.create_index('ix_relationships_from_id_type', 'relationships', ['from_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_from_type'), 'relationships', ['from_type'], unique=False)
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_to_id'), 'relationships', ['to_id'], unique=False)
    op.create_index('ix_relationships_to_id_type', 'relationships', ['to_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_to_type'), 'relationships', ['to_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_to_type'), table_name='relationships')
    op.drop_index('ix_relationships_to_id_type', table_name='relationships')
    op.drop_index(op.f('ix_relationships_to_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_type'), table_name='relationships')
    op.drop_index('ix_relationships_from_id_type', table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
