"""Add timeline_events table

Revision ID: 95d3f2f36019
Revises: 63e7721b9dd0
Create Date: 2026-07-11 15:57:38.640549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95d3f2f36019'
down_revision: Union[str, Sequence[str], None] = '63e7721b9dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_aggregate_id'), 'timeline_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_aggregate_type'), 'timeline_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_correlation_id'), 'timeline_events', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_correlation_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_aggregate_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_aggregate_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    # ### end Alembic commands ###
