"""Add status to captures

Revision ID: 9c018000b7e8
Revises: c857c28ec538
Create Date: 2026-07-11 19:49:34.358914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c018000b7e8'
down_revision: Union[str, Sequence[str], None] = 'c857c28ec538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='PENDING', nullable=False))
    op.create_index(op.f('ix_captures_status'), 'captures', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captures_status'), table_name='captures')
    op.drop_column('captures', 'status')
    # ### end Alembic commands ###
