"""Add collections and memberships tables

Revision ID: bf35be717ff1
Revises: 3fc5a00097d1
Create Date: 2026-07-11 17:23:55.262263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf35be717ff1'
down_revision: Union[str, Sequence[str], None] = '3fc5a00097d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('CAPTURE', 'CONCEPT', 'SOURCE', name='entitytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membership_unique', 'memberships', ['collection_id', 'entity_id', 'entity_type'], unique=True)
    op.create_index(op.f('ix_memberships_collection_id'), 'memberships', ['collection_id'], unique=False)
    op.create_index(op.f('ix_memberships_entity_id'), 'memberships', ['entity_id'], unique=False)
    op.create_index(op.f('ix_memberships_entity_type'), 'memberships', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_entity_type'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_entity_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_collection_id'), table_name='memberships')
    op.drop_index('ix_membership_unique', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
