"""Redesign reviews schema

Revision ID: c857c28ec538
Revises: bf35be717ff1
Create Date: 2026-07-11 18:11:27.824915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c857c28ec538'
down_revision: Union[str, Sequence[str], None] = 'bf35be717ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('CAPTURE', 'CONCEPT', 'SOURCE', name='entitytype'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_due_at', 'reviews', ['due_at'], unique=False)
    op.create_index('ix_reviews_entity_id', 'reviews', ['entity_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.add_column('memberships', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'position')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_entity_id', table_name='reviews')
    op.drop_index('ix_reviews_due_at', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
