from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ascend.domain.reviews.entity import Review


class ReviewRepository(Protocol):
    def save(self, review: Review) -> None: ...

    def get(self, review_id: UUID) -> Review | None: ...

    def delete(self, review_id: UUID) -> None: ...

    def list(self, offset: int = 0, limit: int = 100) -> list[Review]: ...

    def list_by_entity(self, entity_id: UUID) -> list[Review]: ...

    def list_due_reviews(self) -> list[Review]: ...

    def find_active_by_entity_and_type(self, entity_id: UUID, review_type: str) -> Review | None: ...
